name: hacker_news_flutter
description: A new Flutter project.

dependencies:
  hacker_news_client:
    path: ../../hacker_news_client
  hnpwa_client:
    path: ../../hnpwa_client
  http: ^0.11.3+17
  flutter:
    sdk: flutter
  paging: ^0.1.0

  cupertino_icons: ^0.1.2
  isolate: ^2.0.2
  shimmer: ^0.0.4
  url_launcher: ^3.0.3
  flutter_html: ^0.9.4

dev_dependencies:
  flutter_test:
    sdk: flutter

dependency_overrides:
  http: ^0.11.3+17


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Signika
      fonts:
        - asset: fonts/Signika/Signika-Light.ttf
          weight: 300
        - asset: fonts/Signika/Signika-Regular.ttf
          weight: 400
        - asset: fonts/Signika/Signika-Bold.ttf
          weight: 700
    - family: CreteRound
      fonts:
        - asset: fonts/Crete_Round/CreteRound-Regular.ttf
          weight: 400
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
