name: common
description: A starting point for Dart libraries or applications.
# version: 1.0.0
# homepage: https://www.example.com
# author: phillywiggins <email@example.com>

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  rxdart: 0.18.1
  hnpwa_client:
    path: /Users/phillywiggins/lab/hnpwa_client

dev_dependencies:
  test: ^1.3.0
